### ISSUE TITLE
Nested fragments cause flow errors with relay modern

### ISSUE THREAD

**Issue by cdriscol** [facebook/relay#2316]
I'm currently experiencing an issue with flow generated prop types where I'm trying to use flow to set my prop types but I keep getting missing field errors for components that define fragments.  It looks like relay-compiler (as of version 1.5+) is generating the correct types with fragmentRef's, but they do not appear to be working as I would expect.

I used the todo-mvc app to show my problem: https://github.com/cdriscol/relay-todomvc/tree/found-modern-flow

I essentially have the following changes:
```javascript
// @flow
// TodoApp.js
// ...
import type { TodoApp_viewer } from './__generated__/TodoApp_viewer.graphql';
type Props = {
	viewer: TodoApp_viewer,
	children: any,
	relay: any
};

class TodoApp extends React.Component<Props> {
// ...
<TodoListFooter viewer={viewer} />
// ...
}
```

```javascript
// @flow
// TodoListFooter.js
//....
import type { TodoListFooter_viewer } from './__generated__/TodoListFooter_viewer.graphql';

type Props = {
  viewer: TodoListFooter_viewer,
  relay: any,
};

class TodoListFooter extends React.Component<Props> {
//...
}
```

What I'm seeing is 5 errors on the `TodoApp.js`, one of which is the following..
```
Error: src/components/TodoApp.js:42
 42:           <TodoListFooter viewer={viewer} />
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props. This type is incompatible with
 14: class TodoListFooter extends React.Component<Props> {
                                                  ^^^^^ Props. See: src/components/TodoListFooter.js:14
  Property `viewer` is incompatible:
     42:           <TodoListFooter viewer={viewer} />
                                           ^^^^^^ TodoApp_viewer. This type is incompatible with
     10:   viewer: TodoListFooter_viewer,
                   ^^^^^^^^^^^^^^^^^^^^^ TodoListFooter_viewer. See: src/components/TodoListFooter.js:10
      Property `__fragments` is incompatible:
         42:           <TodoListFooter viewer={viewer} />
                                               ^^^^^^ property `__fragments`. Property not found in
         10:   viewer: TodoListFooter_viewer,
                       ^^^^^^^^^^^^^^^^^^^^^ TodoListFooter_viewer. See: src/components/TodoListFooter.js:10
```

I'm wondering why flow cannot handle this case, as the generated flow types do seem to look correct and reference the correct fragment.
```
// TodoApp_viewer.graphql.js
/*::
import type { ConcreteFragment } from 'relay-runtime';
type TodoListFooter_viewer$ref = any;
import type { FragmentReference } from 'relay-runtime';
export opaque type TodoApp_viewer$ref: FragmentReference = FragmentReference;
export type TodoApp_viewer = {|
  +id: string,
  +__fragments: TodoListFooter_viewer$ref,
  +$refType: TodoApp_viewer$ref,
|};
*/
```

```
// TodoListFooter_viewer.graphql.js
/*::
import type { ConcreteFragment } from 'relay-runtime';
import type { FragmentReference } from 'relay-runtime';
export opaque type TodoListFooter_viewer$ref: FragmentReference = FragmentReference;
export type TodoListFooter_viewer = {|
  +todos: ?{|
    +edges: ?$ReadOnlyArray<?{|
      +node: ?{|
        +id: string,
        +complete: ?boolean,
      |},
    |}>,
  |},
  +id: string,
  +numTodos: ?number,
  +numCompletedTodos: ?number,
  +$refType: TodoListFooter_viewer$ref,
|};
*/
```

Sorry for the long explanation and lots of code pasting, I just can't seem to figure out why flow is complaining about the generated types.. maybe I'm missing something here?

**Comment by alloy** [comment]
This is because properly typing fragment references currently only happens when you use the Haste module system. If you’re not at FB, then you’re probably not using that. The issue is that without the Haste module system, it’s hard to import fragment types of your child fragments using the current scheme of colocating artifacts next to the source files (paths are not stable, you may move files around). In short, this is why your fragment ref is typed as `any`, rather than being imported from the child fragment artifact.

I don’t use Flow and would have expected the `any` type to make it at least not complain, but I guess not.

I do use TypeScript and som of us have been working on making Relay-compiler work with that. As part of that effort we also decided to add the option to store all artifacts in a single directory, which enables behavior similarly to using the Haste module system. The PR for it is [here](https://github.com/facebook/relay/pull/2293) and you can read more about the `artifactDirectory` option in this repo https://github.com/relay-tools/relay-compiler-language-typescript

Perhaps you can give that a spin and see if it indeed makes the lives of Flow users easier as well (which we expect, but haven’t yet verified).

**Comment by kikoseijo** [comment]
For me "any" its like a wildcard, you don't benefit of the autocompletion check if you use any, thats the purpose for it.

What I ended up doing its replicate the models as types and just import myself instead of going into the generated folder.

Been trying to figure out how to take the advantage of the GraphQL schema, as them type definitions could be handy on flow, but could not find any info and I ended up writing the types for my models.

**Comment by Nodonisko** [comment]
This is little bit pain, when you want 100% typesafe app. Any ideas?

**Comment by kikoseijo** [comment]
Dont use the __generated__ type definitions.
Use your own types, which are basically a copy of the schema types.

Works great fo me!

**Comment by alloy** [comment]
@cdriscol Were you able to pin point the issue since then?

**Comment by steida** [comment]
The best workaround as far I know.

![screen shot 2018-04-08 at 04 52 33](https://user-images.githubusercontent.com/66249/38462511-b569cc7a-3ae8-11e8-8279-205b86f33a79.png)

**Comment by steida** [comment]
The best workaround as far I know.

![screen shot 2018-04-08 at 04 56 59](https://user-images.githubusercontent.com/66249/38462548-524d2af0-3ae9-11e8-8f9f-5c4d35c3c7d5.png)

**Comment by irrigator** [comment]
I'm pretty sure version 1.4 does not have this issue.

**Comment by sibelius** [comment]
we should learn and document how to use these 2 helpers

`$FragmentRef`: https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayTypes.js#L92

and

`$RelayProps`: https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayTypes.js#L101

**Comment by steida** [comment]
@sibelius Can you send an example to Este please? Thank you.

**Comment by istarkov** [comment]
@sibelius the main problem that it seems like opaque types defined in one file like

```
declare export opaque type Blabla_name$ref: FragmentReference;
```

is not somehow associated with same reference in other file 

```
type Blabla_name$ref = any; <-- this Blabla_name$ref is not the same as opaque Blabla_name$ref
...
+$fragmentRefs: Blabla_name$ref
```

so in this case flow read it as `+$fragmentRefs: any` and accept anything  

Does anybody knew how to link that refs together?

**Comment by istarkov** [comment]
And the main stopper is here https://github.com/facebook/relay/blob/master/packages/relay-compiler/core/RelayFlowGenerator.js#L442
see todo, will try to fix via flowconfig

**Comment by istarkov** [comment]
Can be used now, if change this https://github.com/facebook/relay/blob/master/packages/relay-compiler/bin/RelayCompilerBin.js#L220 `useHaste: true`
Then add all your relay generated folders into 

```
# .flowconfig
[options]
module.system.node.resolve_dirname=./blbal/__generated__
module.system.node.resolve_dirname=./blbalbla/__generated__
...
```
We can use FragmentRef as expected, so there are 2 way to achieve result.
1) Fix todo in link above
2) Allow pass `useHaste` true, and add locally __generated__ dirs to .flowconfig

**Comment by alloy** [comment]
Yup, #2293 will allow fragment reference type checking without using haste.

**Comment by bastoche** [comment]
There is actually a workaround described in the [relay doc](https://facebook.github.io/relay/docs/en/graphql-in-relay.html#relaymask-boolean):
> Applied to a fragment definition, @relay(mask: false) changes the generated Flow types to be better usable when the fragment is included with the same directive. The Flow types will no longer be exact objects and no longer contain internal marker fields.

To be clear, you need to add `@relay(mask: false)` both when defining the fragment:
```js
fragment Todo_todo on Todo @relay(mask: false)
```
 and when using it:
```js
...Todo_todo @relay(mask: false)
```

You will find a working example in [this repository](https://github.com/bastoche/relay-sandbox).

**Comment by steida** [comment]
@bastoche That's very suboptimal.

@alloy What I can do to help?

**Comment by alloy** [comment]
@steida Seeing as my PR that has the single artefact dir feature is now merged and available in the 1.7.0 RC1, it would be great if you could give that version a try and let me know if it works well for you! (See the TS plugin for a configuration example https://github.com/relay-tools/relay-compiler-language-typescript#configuration, which I now realise wasn’t added to the Relay docs, so if everything works out we should document that here.)

**Comment by steida** [comment]
@alloy So I tested it, and it seems nothing has changed.

![screen shot 2018-08-20 at 16 37 55](https://user-images.githubusercontent.com/66249/44347180-78e39d80-a497-11e8-9f24-d442446953e6.png)

Maybe related to https://github.com/facebook/relay/issues/2516

@kassens Should it work OOTB or some another action is required? Thank you.

**Comment by alloy** [comment]
@steida Yes, you should follow the same configuration steps, to get a single artefact directory, for Flow to get fragment references to work. You can find some more explanation [here](https://github.com/facebook/relay/pull/2293#discussion_r170329268) and [https://github.com/facebook/relay/issues/2509](https://github.com/facebook/relay/issues/2509).

**Comment by steida** [comment]
OK, trying it right now. Btw, how single artefact directory should fix Flow types? I think I am missing something.

**Comment by steida** [comment]
There is some Relay black magic I can't figure out how it is supposed to work. Basically, createFragmentContainer lies about what it needs. It needs +$fragmentRefs but it requires props. Damn.

**Comment by steida** [comment]
@kassens Is flow-typed libdefs wrong? Or should we use any recasting? Or something else? It must be one liner, please share it with us. Thank you.

**Comment by richardgirges** [comment]
I upgraded to Flow 0.80.0 and this issue disappeared off the face of the planet. Seems too good to be true. I was originally going with @steida's suggestion, using $FlowFixMe comments everywhere, now they're all yielding "unused suppression" warnings.

Can anyone else confirm that nested fragment defs are working in Flow 0.80.0?

**Comment by steida** [comment]
Probably some error at your side. It still does not work.

**Comment by richardgirges** [comment]
Apologies, I spoke too soon.

The majority of the nested fragment references actually were fixed on my side when I upgraded to flow 0.80.0.

But there are still a few straggling areas where I’m getting the same flow errors and the suppression is still in effect.

Haven’t bothered to understand why some references are working and others aren’t.

**Comment by willisplummer** [comment]
@steida are you still experiencing this problem? i wasn't able to get it to work even using artifacts directory

**Comment by sibelius** [comment]
Try with typescript https://medium.com/@sibelius/relay-modern-migration-to-typescript-c26ab0ee749c

**Comment by RichardLindhout** [comment]
I'm still having this problem when using fragments and I want to generate some things with all sub data from the component.

I would expect the type to be: 
`readonly flowBlocks: ReadonlyArray<FlowBlock_block>;`

but it is
```
readonly flowBlocks: ReadonlyArray<{
        readonly " $fragmentRefs": FlowBlock_flowBlock$ref;
    }>;
```

**Comment by RichardLindhout** [comment]
Ah, probably need the  ReadonlyArray<FlowBlock_flowBlock$ref> 👍 
thanks @sibelius

**Comment by jnak** [comment]
The issue is still happening even though the documentation says [it works](https://relay.dev/docs/en/type-emission#fragment-references). It's most likely because the flow-typed definitions for [createFragmentContainer](https://github.com/flow-typed/flow-typed/blob/c6154227d166c5e752e2c6b8122f84db704563f6/definitions/npm/react-relay_v1.x.x/flow_v0.104.x-/react-relay_v1.x.x.js#L327-L332) are incorrect. Since it's working correctly at Facebook, it would be much appreciated if someone working at Facebook could share the flow definitions Facebook uses. Thanks.

**Comment by simkessy** [comment]
Im seeing this issue on latest relay modern using hooks, is there a recommended solution?

**Comment by jstejada** [comment]
@simkessy could you share exactly what Flow error are you seeing with hooks and an example of your code that produces the error?

**Comment by simkessy** [comment]
@jstejada  this is what im seeing. 
It seems like the counterNoticeModule is coming in as a fragmentRef. 

![image](https://user-images.githubusercontent.com/5871660/115771242-66f1e100-a349-11eb-80db-b7045283f0d1.png)

counterNoticeModule is conditionally included so im wondering if that's why: 

![image](https://user-images.githubusercontent.com/5871660/115771412-986aac80-a349-11eb-8b1a-1c0cf89c1c2f.png)

**Comment by sibelius** [comment]
Migrate to relay hooks, if the issue still valid, open another issue
