### ISSUE TITLE
error involving relay resolver's docblock and fragment name

### ISSUE THREAD

**Issue by ddanielsantos** [facebook/relay#3985]
When a run ``relay-compiler`` it throws the following error in the docblock's rootFragment field:

```bash
$ relay-compiler
[INFO] querying files to compile...
[INFO] [default] compiling...
" not found. Did you mean `oneLine`?t`: ✖︎ Fragment "oneLine

  src/relay/resolvers/LocationOneLine.ts:12:18
    7 │  * @fieldName oneLine
    8 │  * @rootFragment oneLine
      │                  ^^^^^^^
    9 │ 

[ERROR] Compilation failed.
[ERROR] Unable to run relay compiler. Error details:
Failed to build:
 - Validation errors:
" not found. Did you mean `oneLine`?:src/relay/resolvers/LocationOneLine.ts:83:91
```

[Here](https://github.com/ddanielsantos/relay-resolvers/blob/main/web/src/relay/resolvers/LocationOneLine.ts) you can reproduce this error

**Comment by captbaritone** [comment]
@ddanielsantos thanks for the repro!

I tried reproducing with your code and I got a different error:

```
jeldredge@jeldredge-mbp web % yarn relay
yarn run v1.22.18
$ relay-compiler
[INFO] querying files to compile...
[INFO] [default] compiling...
[ERROR] Error in the project `default`: ✖︎ Fragments in graphql tags must start with the module name ('LocationOneLine'). Got 'oneLine' instead.

  src/relay/resolvers/LocationOneLine.ts:12:14
   11 │
   12 │     fragment oneLine on Location {
      │              ^^^^^^^
   13 │       country

[ERROR] Compilation failed.
[ERROR] Unable to run relay compiler. Error details:
Failed to build:
 - Validation errors:
 - Fragments in graphql tags must start with the module name ('LocationOneLine'). Got 'oneLine' instead.:src/relay/resolvers/LocationOneLine.ts:14:21
```

I renamed the fragment (and docblock reference) to `LocationOneLineResolver` and it compiled.

We have had a few bugs that manifested as not being able to find the fragment. These were issues with incremental compilation and would go away when restarting the compiler. When you hit this issue, was it fixed by restarting the compiler?

**Comment by ddanielsantos** [comment]
Sorry for the lack of updates, how can I restart the compiler? I tried reinstalling it but still showed the same error. Anyways, I ran it on another machine, and your solution worked. Thank you 👍🏼
